import * as stylex from '@stylexjs/stylex'

import { color, layout, motion, overlay, radius, shadow, space, text } from '@/tokens/token-consts.stylex'

export const productDemoStyles = stylex.create({
  section: {
    paddingBlock: space.x5xl,
    paddingInline: {
      default: space.xl,
      '@media (min-width: 1200px)': space.x4xl,
    },
  },
  frame: {
    aspectRatio: '16 / 9',
    backgroundColor: color.surfaceSoft,
    borderColor: color.hairlineStrong,
    borderRadius: radius.card,
    borderStyle: 'solid',
    borderWidth: '1px',
    boxShadow: shadow.s2,
    marginInline: 'auto',
    maxWidth: layout.containerWide,
    overflow: 'hidden',
    position: 'relative',
    width: '100%',
  },
  media: {
    height: '100%',
    insetBlockStart: 0,
    insetInlineStart: 0,
    objectFit: 'cover',
    position: 'absolute',
    width: '100%',
  },
  poster: {
    opacity: 1,
    transitionDuration: motion.durationSlow,
    transitionProperty: 'opacity',
    transitionTimingFunction: motion.ease,
  },
  hidden: {
    opacity: 0,
  },
  videoClickable: {
    cursor: 'pointer',
  },
  controls: {
    backdropFilter: 'blur(12px)',
    backgroundColor: overlay.scrim,
    borderRadius: radius.lg,
    insetBlockEnd: space.sm,
    insetInlineEnd: space.sm,
    insetInlineStart: space.sm,
    marginInline: 'auto',
    maxWidth: layout.sidePanelMax,
    padding: space.md,
    position: 'absolute',
  },
  scrubRow: {
    alignItems: 'center',
    display: 'flex',
    gap: space.sm,
    marginBottom: space.sm,
  },
  timeLabel: {
    color: overlay.ink,
    flexShrink: 0,
    fontSize: text.sizeCaption,
  },
  controlsRow: {
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'space-between',
  },
  controlsGroup: {
    alignItems: 'center',
    display: 'flex',
    gap: space.md,
  },
  volumeGroup: {
    alignItems: 'center',
    display: 'flex',
    gap: space.xs,
  },
  iconButton: {
    alignItems: 'center',
    backgroundColor: { ':hover': overlay.hover, default: 'transparent' },
    borderRadius: radius.md,
    color: overlay.ink,
    cursor: 'pointer',
    display: 'flex',
    height: space.xl,
    justifyContent: 'center',
    transitionDuration: motion.durationFast,
    transitionProperty: 'background-color',
    width: space.xl,
    willChange: 'transform',
  },
  speedGroup: {
    alignItems: 'center',
    display: 'flex',
    gap: space.xxs,
  },
  speedButton: {
    backgroundColor: { ':hover': overlay.hover, default: 'transparent' },
    borderRadius: radius.md,
    color: overlay.muted,
    cursor: 'pointer',
    fontSize: text.sizeCaption,
    fontWeight: text.weightMedium,
    paddingBlock: space.xxs,
    paddingInline: space.xs,
    transitionDuration: motion.durationFast,
    transitionProperty: 'background-color, color',
    willChange: 'transform',
  },
  speedButtonActive: {
    backgroundColor: overlay.hover,
    color: overlay.ink,
  },
  sliderTrack: {
    backgroundColor: overlay.track,
    borderRadius: radius.full,
    cursor: 'pointer',
    height: space.xxs,
    position: 'relative',
  },
  scrubTrack: {
    flexGrow: 1,
  },
  volumeTrack: {
    width: space.x4xl,
  },
  sliderFill: {
    backgroundColor: overlay.ink,
    borderRadius: radius.full,
    height: '100%',
    insetBlockStart: 0,
    insetInlineStart: 0,
    position: 'absolute',
    transformOrigin: 'left',
    width: '100%',
  },
})
