import * as stylex from '@stylexjs/stylex'

export const color = stylex.defineConsts({
  brand50: 'var(--portfolio-brand-50)',
  brand600: 'var(--portfolio-brand-600)',
  brand700: 'var(--portfolio-brand-700)',
  brand800: 'var(--portfolio-brand-800)',
  brand900: 'var(--portfolio-brand-900)',
  gray50: 'var(--portfolio-gray-50)',
  gray100: 'var(--portfolio-gray-100)',
  gray200: 'var(--portfolio-gray-200)',
  gray300: 'var(--portfolio-gray-300)',
  gray400: 'var(--portfolio-gray-400)',
  gray500: 'var(--portfolio-gray-500)',
  gray600: 'var(--portfolio-gray-600)',
  gray700: 'var(--portfolio-gray-700)',
  gray800: 'var(--portfolio-gray-800)',
  gray900: 'var(--portfolio-gray-900)',
  gray950: 'var(--portfolio-gray-950)',
  primary: 'var(--portfolio-primary)',
  primaryActive: 'var(--portfolio-primary-active)',
  primaryTint: 'var(--portfolio-primary-tint)',
  primaryDeep: 'var(--portfolio-primary-deep)',
  onPrimary: 'var(--portfolio-on-primary)',
  canvas: 'var(--portfolio-canvas)',
  surfaceCard: 'var(--portfolio-surface-card)',
  surfaceSoft: 'var(--portfolio-surface-soft)',
  surfaceHover: 'var(--portfolio-surface-hover)',
  surfaceNav: 'var(--portfolio-surface-nav)',
  ink: 'var(--portfolio-ink)',
  bodyStrong: 'var(--portfolio-body-strong)',
  body: 'var(--portfolio-body)',
  meta: 'var(--portfolio-meta)',
  captionInk: 'var(--portfolio-caption-ink)',
  hairline: 'var(--portfolio-hairline)',
  hairlineStrong: 'var(--portfolio-hairline-strong)',
  inputBorder: 'var(--portfolio-input-border)',
  positive: 'var(--portfolio-positive)',
  negative: 'var(--portfolio-negative)',
  warning: 'var(--portfolio-warning)',
  neutralFlat: 'var(--portfolio-neutral-flat)',
})

export const overlay = stylex.defineConsts({
  scrim: 'var(--portfolio-overlay-scrim)',
  ink: 'var(--portfolio-overlay-ink)',
  muted: 'var(--portfolio-overlay-muted)',
  hover: 'var(--portfolio-overlay-hover)',
  track: 'var(--portfolio-overlay-track)',
})

export const motion = stylex.defineConsts({
  ease: 'var(--portfolio-ease)',
  easeSpring: 'var(--portfolio-ease-spring)',
  easeSmooth: 'var(--portfolio-ease-smooth)',
  durationFast: 'var(--portfolio-duration-fast)',
  durationMedium: 'var(--portfolio-duration-medium)',
  durationSlow: 'var(--portfolio-duration-slow)',
})

export const text = stylex.defineConsts({
  fontDisplay: 'var(--portfolio-font-display)',
  fontSans: 'var(--portfolio-font-sans)',
  fontMono: 'var(--portfolio-font-mono)',
  sizeDisplayXl: 'var(--portfolio-size-display-xl)',
  sizeDisplayLg: 'var(--portfolio-size-display-lg)',
  sizeDisplayMd: 'var(--portfolio-size-display-md)',
  sizeDisplaySm: 'var(--portfolio-size-display-sm)',
  sizeDisplayXs: 'var(--portfolio-size-display-xs)',
  sizeBodyLg: 'var(--portfolio-size-body-lg)',
  sizeBodyMd: 'var(--portfolio-size-body-md)',
  sizeBodySm: 'var(--portfolio-size-body-sm)',
  sizeCaption: 'var(--portfolio-size-caption)',
  sizeMicro: 'var(--portfolio-size-micro)',
  sizeCode: 'var(--portfolio-size-code)',
  leadingDisplayXl: 'var(--portfolio-leading-display-xl)',
  leadingDisplayLg: 'var(--portfolio-leading-display-lg)',
  leadingDisplayMd: 'var(--portfolio-leading-display-md)',
  leadingDisplaySm: 'var(--portfolio-leading-display-sm)',
  leadingDisplayXs: 'var(--portfolio-leading-display-xs)',
  leadingBodyLg: 'var(--portfolio-leading-body-lg)',
  leadingBodyMd: 'var(--portfolio-leading-body-md)',
  leadingBodySm: 'var(--portfolio-leading-body-sm)',
  leadingCaption: 'var(--portfolio-leading-caption)',
  leadingMicro: 'var(--portfolio-leading-micro)',
  leadingCode: 'var(--portfolio-leading-code)',
  trackingDisplayXl: 'var(--portfolio-tracking-display-xl)',
  trackingDisplayLg: 'var(--portfolio-tracking-display-lg)',
  trackingDisplayMd: 'var(--portfolio-tracking-display-md)',
  trackingDisplaySm: 'var(--portfolio-tracking-display-sm)',
  trackingDisplayXs: 'var(--portfolio-tracking-display-xs)',
  trackingBody: 'var(--portfolio-tracking-body)',
  trackingBodySm: 'var(--portfolio-tracking-body-sm)',
  trackingLabel: 'var(--portfolio-tracking-label)',
  trackingEyebrow: 'var(--portfolio-tracking-eyebrow)',
  trackingAllcaps: 'var(--portfolio-tracking-allcaps)',
  weightRegular: 'var(--portfolio-weight-regular)',
  weightMedium: 'var(--portfolio-weight-medium)',
  weightSemibold: 'var(--portfolio-weight-semibold)',
})

export const space = stylex.defineConsts({
  xxs: 'var(--portfolio-space-xxs)',
  xs: 'var(--portfolio-space-xs)',
  sm: 'var(--portfolio-space-sm)',
  md: 'var(--portfolio-space-md)',
  lg: 'var(--portfolio-space-lg)',
  xl: 'var(--portfolio-space-xl)',
  x2xl: 'var(--portfolio-space-2xl)',
  x3xl: 'var(--portfolio-space-3xl)',
  x4xl: 'var(--portfolio-space-4xl)',
  x5xl: 'var(--portfolio-space-5xl)',
  x6xl: 'var(--portfolio-space-6xl)',
  section: 'var(--portfolio-space-section)',
})

export const radius = stylex.defineConsts({
  none: 'var(--portfolio-radius-none)',
  xs: 'var(--portfolio-radius-xs)',
  sm: 'var(--portfolio-radius-sm)',
  md: 'var(--portfolio-radius-md)',
  lg: 'var(--portfolio-radius-lg)',
  xl: 'var(--portfolio-radius-xl)',
  pillSm: 'var(--portfolio-radius-pill-sm)',
  pill: 'var(--portfolio-radius-pill)',
  full: 'var(--portfolio-radius-full)',
  card: 'var(--portfolio-radius-card)',
  input: 'var(--portfolio-radius-input)',
  action: 'var(--portfolio-radius-action)',
  pulse: 'var(--portfolio-radius-pulse)',
})

export const shadow = stylex.defineConsts({
  s0: 'var(--portfolio-shadow-0)',
  s1: 'var(--portfolio-shadow-1)',
  s2: 'var(--portfolio-shadow-2)',
  s3: 'var(--portfolio-shadow-3)',
  s4: 'var(--portfolio-shadow-4)',
  s5: 'var(--portfolio-shadow-5)',
  float: 'var(--portfolio-shadow-float)',
  modal: 'var(--portfolio-shadow-modal)',
})

export const layout = stylex.defineConsts({
  containerMax: 'var(--portfolio-container-max)',
  containerWide: 'var(--portfolio-container-wide)',
  proseMax: 'var(--portfolio-prose-max)',
  measureProse: 'var(--portfolio-measure-prose)',
  sidePanelMax: 'var(--portfolio-side-panel-max)',
  focusRing: 'var(--portfolio-focus-ring)',
})
